Update Linting-ps1.yml

diff --git a/.github/workflows/Linting-ps1.yml b/.github/workflows/Linting-ps1.yml
--- a/.github/workflows/Linting-ps1.yml
+++ b/.github/workflows/Linting-ps1.yml
@@ -60,11 +60,11 @@ jobs:
               with:
                   submodules: true
 
-            - name: Install linting dependencies
-              id: dependencies
-              run: |
-                  Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
-                  Install-LintingDependencies -PathToLintersSubmodulesRoot '${{ inputs.path_to_linters_submodule_root }}' -Verbose
+            # - name: Install linting dependencies
+            #   id: dependencies
+            #   run: |
+            #       Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
+            #       Install-LintingDependencies -PathToLintersSubmodulesRoot '${{ inputs.path_to_linters_submodule_root }}' -Verbose
 
             # - name: Run gitignore linter
             #   if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_gitignore_linter
@@ -103,7 +103,7 @@ jobs:
             #       Test-CodeUsingPSScriptAnalyzer -PathToLintersSubmodulesRoot '${{ inputs.path_to_linters_submodule_root }}' -Verbose
 
             - name: Run clang tools
-              if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_clang_tools_linter
+            #   if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_clang_tools_linter
               shell: bash
               run: |
                 cmake --version
