Update Linting-ps1.yml

diff --git a/.github/workflows/Linting-ps1.yml b/.github/workflows/Linting-ps1.yml
--- a/.github/workflows/Linting-ps1.yml
+++ b/.github/workflows/Linting-ps1.yml
@@ -66,41 +66,41 @@ jobs:
                   Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
                   Install-LintingDependencies -PathToLintersSubmodulesRoot '${{ inputs.path_to_linters_submodule_root }}' -Verbose
 
-            - name: Run gitignore linter
-              if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_gitignore_linter
-              run: |
-                  Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
-                  Test-GitIgnoreFile -Verbose
+            # - name: Run gitignore linter
+            #   if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_gitignore_linter
+            #   run: |
+            #       Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
+            #       Test-GitIgnoreFile -Verbose
 
-            - name: Run gitattributes linter
-              if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_gitattributes_linter
-              run: |
-                  Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
-                  Test-GitAttributesFile -Verbose
+            # - name: Run gitattributes linter
+            #   if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_gitattributes_linter
+            #   run: |
+            #       Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
+            #       Test-GitAttributesFile -Verbose
 
-            - name: Run cspell configuration linter
-              if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_cspell_configuration_linter
-              run: |
-                  Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
-                  Test-CSpellConfigurationFile -Verbose
+            # - name: Run cspell configuration linter
+            #   if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_cspell_configuration_linter
+            #   run: |
+            #       Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
+            #       Test-CSpellConfigurationFile -Verbose
 
-            - name: Run cspell
-              if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_cspell_linter
-              run: |
-                  Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
-                  Test-CodeUsingCSpell -PathToLintersSubmodulesRoot '${{ inputs.path_to_linters_submodule_root }}' -PathBackToRepositoryRoot '${{ inputs.path_back_to_repository_root }}' -Verbose
+            # - name: Run cspell
+            #   if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_cspell_linter
+            #   run: |
+            #       Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
+            #       Test-CodeUsingCSpell -PathToLintersSubmodulesRoot '${{ inputs.path_to_linters_submodule_root }}' -PathBackToRepositoryRoot '${{ inputs.path_back_to_repository_root }}' -Verbose
 
-            - name: Run prettier
-              if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_prettier_linter
-              run: |
-                  Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
-                  Test-CodeUsingPrettier -PathToLintersSubmodulesRoot '${{ inputs.path_to_linters_submodule_root }}' -PathBackToRepositoryRoot '${{ inputs.path_back_to_repository_root }}' -Verbose
+            # - name: Run prettier
+            #   if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_prettier_linter
+            #   run: |
+            #       Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
+            #       Test-CodeUsingPrettier -PathToLintersSubmodulesRoot '${{ inputs.path_to_linters_submodule_root }}' -PathBackToRepositoryRoot '${{ inputs.path_back_to_repository_root }}' -Verbose
 
-            - name: Run PSScriptAnalyzer
-              if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_psscript_analyzer_linter
-              run: |
-                  Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
-                  Test-CodeUsingPSScriptAnalyzer -PathToLintersSubmodulesRoot '${{ inputs.path_to_linters_submodule_root }}' -Verbose
+            # - name: Run PSScriptAnalyzer
+            #   if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_psscript_analyzer_linter
+            #   run: |
+            #       Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1
+            #       Test-CodeUsingPSScriptAnalyzer -PathToLintersSubmodulesRoot '${{ inputs.path_to_linters_submodule_root }}' -Verbose
 
             - name: Run clang tools
               if: (success() || failure()) && steps.dependencies.outcome == 'success' && inputs.run_clang_tools_linter
@@ -109,6 +109,7 @@ jobs:
                   # Install the ninja and the latest version of clang-tidy and clang-format
                   if [ ${{ matrix.os }} = macos-latest ]
                   then
+                      brew install cmake
                       brew install ninja
                       brew install llvm
                       # Override pre-installed clang by adding to the path
@@ -135,7 +136,7 @@ jobs:
                   fi
 
                   # Configure CMake to create the 'compile_commands.json' file
-                  cmake -S ${{ inputs.path_back_to_repository_root }} -B ./build -G 'Ninja'
+                  cmake -S . -B ./build -G 'Ninja'
 
                   pwsh -command 'Import-Module ${{ inputs.path_to_linters_submodule_root }}/linters-ps1/Linters.psd1'
                   pwsh -command 'Test-CodeUsingClangTools -PathToLintersSubmodulesRoot ${{ inputs.path_to_linters_submodule_root }} -Verbose'
